### ISSUE TITLE
Improve configuration

### ISSUE THREAD

**Issue by escodebar** [adfinis-sygroup/timed-backend#267]
I took a look at your [instructions for installation](https://github.com/adfinis-sygroup/timed-backend#installation), [settings.py](https://github.com/adfinis-sygroup/timed-backend/blob/bafcb14ada6d1739d91dd178405961536824e718/timed/settings.py) and #8
I believe this can be improved.

Further lecture: https://12factor.net/config

# Environment variables

You use a single `.env` file.
I would define `.env`-files for each environment: `.env.development`, `.env.test`, `.env.build` etc.
Each of them contains the configuration settings for each environment.
To avoid repeating the configuration definitions, a `.env.base` may be defined, the more specific `.env.*` files then define a more specific set of settings.
I would use `.env` just to override the configuration settings of the other files (and for production - i.e. there should be no `.env.production`).
Also add a `.env.template` which contains the required configuration variables to deploy the application, to simplify operations' tasks (when creating the `.env.production`).
I would also use [`dotenv`](https://github.com/theskumar/python-dotenv) to load these environment variables.

# Modes

It would be great if the settings for each environment were kept in classes using [`django classy settings`](https://github.com/funkybob/django-classy-settings).
Then you can define the settings required in production only in the production class (for instance a sentry backend).
This also allows to set defaults per environment (like the secret key, the database host, etc.) in the class - yet I do not recommend to do so and rather keep the settings in the environment specific `.env`-file (read further lecture).

**Comment by sliverc** [comment]
The README was not really that clear which is fixed in #271 but `.env` should only be used in development mode and the same with the `ENV` environment variable. Having different files for different servers would also defeat the point of 12factor, however there is the `DJANGO_ENV_FILE` environment variable where a custom environment file can be defined (is now also documented).

We use [django-environ](https://github.com/joke2k/django-environ) which already decouples required fields from development and production environment. e.g. settings `SECRET_KEY` is needed in to be set in produduction but not in development.

Hope this clarifies. Closing ticket but please comment if things are still unclear.
